# Generated by Django 5.1.1 on 2024-09-13 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_published', models.IntegerField()),
                ('borrow_time', models.IntegerField(choices=[(10, 'Type_1'), (5, 'Type_2'), (2, 'Type_3')], default=10)),
                ('filename', models.ImageField(blank=True, upload_to='book_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('erased', 'Erased')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(default=datetime.date(2024, 9, 13))),
                ('return_date', models.DateField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
